name: Android CI

on:
  push:
    branches:
      - main
      - develop
      - release/**
  pull_request:
    branches:
      - main
      - develop
      - release/**

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Create google-services.json
      run: echo '${{ secrets.GOOGLE_SERVICES_JSON }}' > app/google-services.json
    - name: Build with Gradle
      run: ./gradlew build
